### ISSUE TITLE
Please release the held-out dataset

### ISSUE THREAD

**Issue by avidale** [deep-spin/hallucinations-in-nmt#2]
Hello Nuno!
I am trying now to reproduce [the Optimal transport paper](https://arxiv.org/abs/2212.09631), and it refers to the filtered held-out dataset from this repository. 

However, the readme here contains only the link to the training subset. Could you please also share the filtered held-out subset that you use in the both papers?

**Comment by nunonmg** [comment]
Hi @avidale, all necessary resources to reproduce the Optimal Transport paper are in https://github.com/deep-spin/ot-hallucination-detection
